import { Injectable, NotFoundException, OnModuleInit } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import { unlink } from 'node:fs/promises';
import path from 'node:path';

interface CreateVesteDto {
  titre: string;
  description: string;
}

interface UpdateVesteDto {
  titre: string;
  description: string;
}

interface VesteRecord {
  id: number;
  titre: string;
  description: string;
  isPublished: boolean;
  createdAt: string;
  updatedAt: string;
}

interface VesteImageRecord {
  id: number;
  vesteId: number;
  mediaUrl: string;
  mediaType: string;
  fileSize: number;
  createdAt: string;
  updatedAt: string;
}

interface VesteWithImagesRecord extends VesteRecord {
  images: VesteImageRecord[];
}

@Injectable()
export class VestesService implements OnModuleInit {
  constructor(private readonly db: DatabaseService) {}

  async onModuleInit() {
    await this.db.execute(`
      CREATE TABLE IF NOT EXISTS Veste (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        titre TEXT NOT NULL,
        description TEXT NOT NULL,
        isPublished BOOLEAN NOT NULL DEFAULT false,
        createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await this.db.execute(`
      CREATE TABLE IF NOT EXISTS VesteImage (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        vesteId INT NOT NULL,
        mediaUrl TEXT NOT NULL,
        mediaType TEXT NOT NULL,
        fileSize INT NOT NULL DEFAULT 0,
        createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_veste_image_veste
          FOREIGN KEY (vesteId) REFERENCES Veste(id) ON DELETE CASCADE
      )
    `);

    await this.db.execute(`
      CREATE INDEX IF NOT EXISTS idx_veste_image_vesteId ON VesteImage(vesteId)
    `);

    await this.db.execute(
      `
      INSERT INTO Veste (id, titre, description, isPublished, createdAt, updatedAt)
      VALUES
        (8, ?, ?, TRUE, ?::timestamptz, ?::timestamptz),
        (9, ?, ?, TRUE, ?::timestamptz, ?::timestamptz),
        (10, ?, ?, TRUE, ?::timestamptz, ?::timestamptz),
        (11, ?, ?, TRUE, ?::timestamptz, ?::timestamptz)
      ON CONFLICT (id) DO NOTHING
      `,
      [
        'Collection Homme TISSU',
        'style rapide',
        '2026-04-02 10:58:46.000',
        '2026-04-02 11:01:46.000',
        'Veste Maron',
        'rapide est simple a entretenir',
        '2026-04-02 10:59:35.000',
        '2026-04-02 11:01:38.000',
        'veste couleur cendre',
        'disponible',
        '2026-04-02 11:00:13.000',
        '2026-04-02 11:01:33.000',
        'veste  ojgtdsdscdc',
        'jhdgvsccsvsvvs',
        '2026-04-02 11:00:55.000',
        '2026-04-02 13:07:04.000',
      ],
    );

    await this.db.execute(
      `
      INSERT INTO VesteImage (id, vesteId, mediaUrl, mediaType, fileSize, createdAt, updatedAt)
      VALUES
        (11, 8, ?, ?, ?, ?::timestamptz, ?::timestamptz),
        (12, 8, ?, ?, ?, ?::timestamptz, ?::timestamptz),
        (13, 8, ?, ?, ?, ?::timestamptz, ?::timestamptz),
        (14, 9, ?, ?, ?, ?::timestamptz, ?::timestamptz),
        (15, 10, ?, ?, ?, ?::timestamptz, ?::timestamptz),
        (16, 11, ?, ?, ?, ?::timestamptz, ?::timestamptz),
        (19, 11, ?, ?, ?, ?::timestamptz, ?::timestamptz)
      ON CONFLICT (id) DO NOTHING
      `,
      [
        '/uploads/1775127526747-IMG-20260401-WA0008.jpg',
        'image',
        65588,
        '2026-04-02 10:58:46.000',
        '2026-04-02 10:58:46.000',
        '/uploads/1775127526829-IMG-20260401-WA0009.jpg',
        'image',
        90356,
        '2026-04-02 10:58:46.000',
        '2026-04-02 10:58:46.000',
        '/uploads/1775127526951-IMG-20260401-WA0011.jpg',
        'image',
        98470,
        '2026-04-02 10:58:47.000',
        '2026-04-02 10:58:47.000',
        '/uploads/1775127575286-IMG-20260401-WA0008.jpg',
        'image',
        65588,
        '2026-04-02 10:59:35.000',
        '2026-04-02 10:59:35.000',
        '/uploads/1775127613861-IMG-20260401-WA0009.jpg',
        'image',
        90356,
        '2026-04-02 11:00:13.000',
        '2026-04-02 11:00:13.000',
        '/uploads/1775127656104-IMG-20260401-WA0011.jpg',
        'image',
        98470,
        '2026-04-02 11:00:56.000',
        '2026-04-02 11:00:56.000',
        '/uploads/1775135216949-2ee226baa9707d1e8ca4df21ae7c34f84084dcab_1651443_TL_WR840N_image4.jpg',
        'image',
        83524,
        '2026-04-02 13:06:57.000',
        '2026-04-02 13:06:57.000',
      ],
    );

    await this.db.execute(
      `
      SELECT setval(
        pg_get_serial_sequence('Veste', 'id'),
        COALESCE((SELECT MAX(id) FROM Veste), 1),
        true
      )
      `,
    );

    await this.db.execute(
      `
      SELECT setval(
        pg_get_serial_sequence('VesteImage', 'id'),
        COALESCE((SELECT MAX(id) FROM VesteImage), 1),
        true
      )
      `,
    );
  }

  private async withImages(veste: VesteRecord): Promise<VesteWithImagesRecord> {
    const images = await this.db.query<VesteImageRecord>(
      'SELECT * FROM VesteImage WHERE vesteId = ? ORDER BY createdAt ASC',
      [veste.id],
    );

    return { ...veste, images };
  }

  async create(dto: CreateVesteDto): Promise<VesteWithImagesRecord> {
    await this.db.execute(
      'INSERT INTO Veste (titre, description, isPublished, createdAt, updatedAt) VALUES (?, ?, false, NOW(), NOW())',
      [dto.titre, dto.description],
    );

    const rows = await this.db.query<VesteRecord>(
      'SELECT * FROM Veste ORDER BY id DESC LIMIT 1',
    );

    return this.withImages(rows[0]);
  }

  async addImage(
    vesteId: number,
    mediaUrl: string,
    mediaType: string,
    fileSize: number,
  ) {
    const vesteRows = await this.db.query<{ id: number }>(
      'SELECT id FROM Veste WHERE id = ? LIMIT 1',
      [vesteId],
    );
    if (!vesteRows[0]) {
      throw new NotFoundException('Modele introuvable');
    }

    await this.db.execute(
      'INSERT INTO VesteImage (vesteId, mediaUrl, mediaType, fileSize, createdAt, updatedAt) VALUES (?, ?, ?, ?, NOW(), NOW())',
      [vesteId, mediaUrl, mediaType, fileSize],
    );

    return this.getById(vesteId);
  }

  async removeImage(imageId: number) {
    const imageRows = await this.db.query<{ id: number; mediaUrl: string }>(
      'SELECT id, mediaUrl FROM VesteImage WHERE id = ? LIMIT 1',
      [imageId],
    );
    const image = imageRows[0];

    if (!image) {
      throw new NotFoundException('Image introuvable');
    }

    await this.db.execute('DELETE FROM VesteImage WHERE id = ?', [imageId]);

    if (image.mediaUrl.startsWith('/uploads/')) {
      const filePath = path.join(
        process.cwd(),
        image.mediaUrl.replace(/^\//, ''),
      );
      try {
        await unlink(filePath);
      } catch {
        // Ignore missing file errors.
      }
    }

    return { message: 'Image supprimee' };
  }

  async findPublic(): Promise<VesteWithImagesRecord[]> {
    const rows = await this.db.query<VesteRecord>(
      'SELECT * FROM Veste WHERE isPublished = true ORDER BY createdAt DESC',
    );
    return Promise.all(rows.map((row) => this.withImages(row)));
  }

  async findAdmin(): Promise<VesteWithImagesRecord[]> {
    const rows = await this.db.query<VesteRecord>(
      'SELECT * FROM Veste ORDER BY createdAt DESC',
    );
    return Promise.all(rows.map((row) => this.withImages(row)));
  }

  async getById(id: number): Promise<VesteWithImagesRecord> {
    const rows = await this.db.query<VesteRecord>(
      'SELECT * FROM Veste WHERE id = ? LIMIT 1',
      [id],
    );
    const veste = rows[0];
    if (!veste) {
      throw new NotFoundException('Modele introuvable');
    }

    return this.withImages(veste);
  }

  async setPublished(id: number, isPublished: boolean) {
    const vesteRows = await this.db.query<{ id: number }>(
      'SELECT id FROM Veste WHERE id = ? LIMIT 1',
      [id],
    );
    if (!vesteRows[0]) {
      throw new NotFoundException('Modele introuvable');
    }

    await this.db.execute(
      'UPDATE Veste SET isPublished = ?, updatedAt = NOW() WHERE id = ?',
      [isPublished, id],
    );

    return this.getById(id);
  }

  async update(id: number, dto: UpdateVesteDto) {
    const vesteRows = await this.db.query<{ id: number }>(
      'SELECT id FROM Veste WHERE id = ? LIMIT 1',
      [id],
    );
    if (!vesteRows[0]) {
      throw new NotFoundException('Modele introuvable');
    }

    await this.db.execute(
      'UPDATE Veste SET titre = ?, description = ?, updatedAt = NOW() WHERE id = ?',
      [dto.titre, dto.description, id],
    );

    return this.getById(id);
  }

  async remove(id: number) {
    const vesteRows = await this.db.query<{ id: number }>(
      'SELECT id FROM Veste WHERE id = ? LIMIT 1',
      [id],
    );
    if (!vesteRows[0]) {
      throw new NotFoundException('Modele introuvable');
    }

    const imageRows = await this.db.query<{ mediaUrl: string }>(
      'SELECT mediaUrl FROM VesteImage WHERE vesteId = ?',
      [id],
    );

    await this.db.execute('DELETE FROM Veste WHERE id = ?', [id]);

    for (const image of imageRows) {
      if (image.mediaUrl.startsWith('/uploads/')) {
        const filePath = path.join(
          process.cwd(),
          image.mediaUrl.replace(/^\//, ''),
        );
        try {
          await unlink(filePath);
        } catch {
          // Ignore missing file errors.
        }
      }
    }

    return { message: 'Modele supprime' };
  }
}
