import {
  BadRequestException,
  ConflictException,
  Injectable,
  OnModuleInit,
  UnauthorizedException,
} from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';

interface LoginPayload {
  email: string;
  password: string;
}

interface BootstrapPayload {
  email: string;
  password: string;
}

interface UpdateCredentialsPayload {
  email: string;
  password: string;
}

interface AdminAuthRow {
  id: number;
  email: string;
  password: string;
}

@Injectable()
export class AuthService implements OnModuleInit {
  constructor(private readonly db: DatabaseService) {}

  async onModuleInit() {
    await this.db.execute(`
      CREATE TABLE IF NOT EXISTS Admin (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR(255) NOT NULL UNIQUE,
        password TEXT NOT NULL,
        createdAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await this.db.execute(
      `
      INSERT INTO Admin (id, email, password, createdAt, updatedAt)
      VALUES (1, ?, ?, ?::timestamptz, ?::timestamptz)
      ON CONFLICT (id) DO NOTHING
      `,
      [
        'millermwr@gmail.com',
        '$2b$10$hFTeh4qMDvNAFNvuNf1JdeECpZEd2wPemb/udZm7aUQ/14P8sofiW',
        '2026-04-02 09:25:36.000',
        '2026-04-02 09:25:36.000',
      ],
    );

    await this.db.execute(
      `
      SELECT setval(
        pg_get_serial_sequence('Admin', 'id'),
        COALESCE((SELECT MAX(id) FROM Admin), 1),
        true
      )
      `,
    );
  }

  private getJwtSecret() {
    return process.env.JWT_SECRET || 'atelier-secret-change-me';
  }

  private signToken(adminId: number, email: string) {
    return jwt.sign(
      { sub: adminId, email, role: 'admin' },
      this.getJwtSecret(),
      {
        expiresIn: '48h',
      },
    );
  }

  async bootstrapAdmin(payload: BootstrapPayload) {
    if (!payload.email || !payload.password) {
      throw new BadRequestException('Email et mot de passe requis');
    }

    const countRows = await this.db.query<{ count: number }>(
      'SELECT COUNT(*) as count FROM Admin',
    );
    const adminCount = Number(countRows[0]?.count ?? 0);

    if (adminCount > 0) {
      throw new ConflictException('Un administrateur existe deja');
    }

    const hashedPassword = await bcrypt.hash(payload.password, 10);
    await this.db.execute(
      'INSERT INTO Admin (email, password, createdAt, updatedAt) VALUES (?, ?, NOW(), NOW())',
      [payload.email.toLowerCase().trim(), hashedPassword],
    );
    
    const adminRows = await this.db.query<{ id: number; email: string }>(
      'SELECT id, email FROM Admin WHERE email = ? LIMIT 1',
      [payload.email.toLowerCase().trim()],
    );
    const admin = adminRows[0];

    return {
      message: 'Administrateur cree avec succes',
      admin: {
        id: admin.id,
        email: admin.email,
      },
    };
  }

  async login(payload: LoginPayload) {
    if (!payload.email || !payload.password) {
      throw new BadRequestException('Email et mot de passe requis');
    }

    const admins = await this.db.query<AdminAuthRow>(
      'SELECT id, email, password FROM Admin WHERE email = ? LIMIT 1',
      [payload.email.toLowerCase().trim()],
    );
    const admin = admins[0];

    if (!admin) {
      throw new UnauthorizedException('Identifiants invalides');
    }

    const isValidPassword = await bcrypt.compare(
      payload.password,
      admin.password,
    );
    if (!isValidPassword) {
      throw new UnauthorizedException('Identifiants invalides');
    }

    return {
      token: this.signToken(admin.id, admin.email),
      admin: {
        id: admin.id,
        email: admin.email,
      },
    };
  }

  async checkAdminExists(): Promise<boolean> {
    const countRows = await this.db.query<{ count: number }>(
      'SELECT COUNT(*) as count FROM Admin',
    );
    const adminCount = Number(countRows[0]?.count ?? 0);
    return adminCount > 0;
  }

  async updateCredentials(adminId: number, payload: UpdateCredentialsPayload) {
    const nextEmail = payload.email?.toLowerCase().trim();
    const nextPassword = payload.password?.trim();

    if (!nextEmail || !nextPassword) {
      throw new BadRequestException('Email et mot de passe requis');
    }

    if (nextPassword.length < 6) {
      throw new BadRequestException('Le mot de passe doit contenir au moins 6 caracteres');
    }

    const existingEmailRows = await this.db.query<{ id: number }>(
      'SELECT id FROM Admin WHERE email = ? AND id <> ? LIMIT 1',
      [nextEmail, adminId],
    );
    if (existingEmailRows.length > 0) {
      throw new ConflictException('Cet email est deja utilise');
    }

    const hashedPassword = await bcrypt.hash(nextPassword, 10);
    await this.db.execute(
      'UPDATE Admin SET email = ?, password = ?, updatedAt = NOW() WHERE id = ?',
      [nextEmail, hashedPassword, adminId],
    );
    
    const updatedRows = await this.db.query<{ id: number; email: string }>(
      'SELECT id, email FROM Admin WHERE id = ? LIMIT 1',
      [adminId],
    );
    const admin = updatedRows[0];

    if (!admin) {
      throw new UnauthorizedException('Administrateur introuvable');
    }

    return {
      message: 'Identifiants mis a jour avec succes',
      token: this.signToken(admin.id, admin.email),
      admin: {
        id: admin.id,
        email: admin.email,
      },
    };
  }
}
